### PR TITLE
chore: prevent from style injection to explode in server side rendering

### PR DESCRIPTION
**Pull request by shlomitc**
Solve the errors thrown
https://github.com/mondaycom/monday-ui-react-core/issues/1203#issuecomment-1658912659

Errors that appeared before:
image

### CODE REVIEW

**Review by YossiSaadi — APPROVED** [review]
does it have any affect on non-SSR?

**Comment by shlomitc** [comment]
@YossiSaadi - shouldn't do any harm since it's just validating it actually exists, but do you think of other ways to break it?

**Comment by YossiSaadi** [comment]
> @YossiSaadi - shouldn't do any harm since it's just validating it actually exists, but do you think of other ways to break it?

Hmm..
I actually guess it does not have any affect, otherwise we would already see it break if document did not exist

**Comment by shlomitc** [comment]
@YossiSaadi - not sure we would see it since this script injection logic isn't used in the storybook

**Comment by YossiSaadi** [comment]
> @YossiSaadi - not sure we would see it since this script injection logic isn't used in the storybook

unfortunately, I'm not familiar enough with this so I'll might suggest @hadasfa and @SergeyRoyt to also give their input on this one

**Pull request merged**
