### PR TITLE
feat: Align vibe's colors to new a11y based colors

### PR DESCRIPTION
**Pull request by MBYOded**
As part of Monday's effort to make our customers experience as accessible as possible we've decided to update some of our colors to be `AAA` accessible and empower our costumers with sight impairment with a better more suitable experience.

https://monday.monday.com/docs/5264487294

### CODE REVIEW

**Comment by YossiSaadi** [comment]
Hey @MBYOded ! long time :)
seems cool, but just to make sure - those changes were approved/requested by Vibe designers?

**Comment by MBYOded** [comment]
> Hey @MBYOded ! long time :) seems cool, but just to make sure - those changes were approved/requested by Vibe designers?

@YossiSaadi my man, 
Sure thing, Meirav asked me to change here as well.
We're doing a A11y change that affects most of our code base and we needed to reflect it here as well

**Review by YossiSaadi — APPROVED** [review]
Awesome!

**Comment by YossiSaadi** [comment]
> > Hey @MBYOded ! long time :) seems cool, but just to make sure - those changes were approved/requested by Vibe designers?
> 
> @YossiSaadi my man, Sure thing, Meirav asked me to change here as well. We're doing a A11y change that affects most of our code base and we needed to reflect it here as well

Bless you 🙏🏼

**Comment by talkor** [comment]
@MBYOded you need to also change the colors in the theme sass files (packages/style/src/Themes)

**Review by talkor — APPROVED** [review]

**Pull request merged**
