### PR TITLE
Bugfix: Disabled button no longer showing a not-allowed cursor #774

### LINKED ISSUE #774: Disabled button no longer showing a not-allowed cursor
Due to `pointer-events: none;` `cursor: not-allowed` is no longer working

### PR DESCRIPTION
**Pull request by vczb**
- Remove pointer events none
  - Add disabled attribute
  - Update snapshot

---

## Bug reason: 

the bug is happen because is not possible use cursor styles and pointer-events:none together.

## Implementation:

I have been removed the `pointer-events` and added a `disable` html attribute to the button ( that improve the semantic HTML and avoid the click event ).

Also, I have been addeded `monday-style-button--prevent-click-animation` className when is disabled to prevent the click animation

After the changes I update the snapshots 

---

#### Basic
- [x] Used plop (`npm run plop`) to create a new component.
- [x] PR has description.
- [x] New component is functional and uses Hooks. 
- [x] Component defines [`PropTypes`](https://reactjs.org/docs/typechecking-with-proptypes.html).
#### Style
- [x] Styles are added to `NewComponent.modules.scss` file inside of the `NewComponent` folder.
- [x] Component uses CSS Modules.
- [x] Design is compatible with [Monday Design System](https://design.monday.com/).
#### Storybook
- [x] Stories were added to `/src/NewComponent/__stories__/NewComponent.stories.js` file.
- [x] Stories include all flows of using the component.
#### Tests
- [x] Tests are compliant with [TESTING_README.md](TESTING_README.md) instructions.

----

Close #774

### CODE REVIEW

**Review by orrgottlieb — CHANGES_REQUESTED** [review]
hello @vczb thank you so much for the detailed PR and Description
there is an issue with onMouseLeave while a button is disabled -
you can see the following [thread](https://codesandbox.io/s/gracious-galileo-qymqw?file=/src/App.js)

They have solved it with changing the `onMouseLeave` and `onMouseEnter` to `onPointerLeave` and `onPointerEnter`


The reason we added the `pointer-events: none` was to solve an issue we had with our dialog component who listens to event on the "origin" element

So, your solution will work but we will have a bug in our dialog component

**Comment by vczb** [comment]
> onPointerLeave

Hi @orrgottlieb thanks for the clarification. What you think about override the `onPointerEnter` and `onPointerLeave` and check if is disabled? 

Somethink like [this example](https://codesandbox.io/s/button-disable-events-zt2noh?file=/src/App.js)

**Comment by orrgottlieb** [comment]
@vczb i think you can change the `onMouseEnter` to `onPointerEnter` - we would need to check it, but i think it will do the work

**Comment by vczb** [comment]
> we would need to check it, but i think it

I already update the PR, I believe that will work as expected, please test it and let me know if any change is needed

**Comment by vczb** [comment]
> @vczb i think you can change the `onMouseEnter` to `onPointerEnter` - we would need to check it, but i think it will do the work

hi @orrgottlieb let me know if you need more changes if not I will only fix the conflicts

**Comment by shlomitc** [comment]
This PR has been stale for a while so I'm closing it. Thanks

**Pull request closed without merging**
