### PR TITLE
docs: add virtualized grid description and component

### PR DESCRIPTION
**Pull request by Suraj-Bhandarkar-S**
#1810

To Add [VirtualizedGrid](https://style.monday.com/?path=/docs/navigation-virtualizedgrid--docs) component example to COMPONENTS_DESCRIPTIONS_ENTRIES array so it'd appear on [components catalog page](https://style.monday.com/?path=/docs/catalog--catalog)

Screen Shot:
295588715-04ae06f4-9122-45a6-9c4f-91f521c901f0

Based on the previous request in https://github.com/mondaycom/monday-ui-react-core/pull/1823

Added:
- two rows of items
- 50 items in total

#1886 
continued from the closed PR with a new request. Had to update the git branch with only the the required changes.

Thank you @YossiSaadi  for the help :). Also, Let me know if I need to make any changes for the current PR.

### CODE REVIEW

**Review by YossiSaadi — COMMENTED** [review]
Amazing @Suraj-Bhandarkar-S !
Notice that one of the files fails for lint (prettier)
Let's run prettier on that file, commit it and merge that PR! :)

**Comment by Suraj-Bhandarkar-S** [comment]
I updated the file causing the issue, hopefully that fixed it :)

**Comment by YossiSaadi** [comment]
> I updated the file causing the issue, hopefully that fixed it :)

Awesome! 👏🏻

**Review by YossiSaadi — APPROVED** [review]
Well done!

**Pull request merged**
