### PR TITLE
fix: <BreadcrumbsBar> - should be clickable only if type = Navigation #1569

### PR DESCRIPTION
**Pull request by SoumyadiptoPal**
Fixes Issue #1569

#### Basic

- [x] Used plop (`npm run plop`) to create a new component.
- [x] PR has description.
- [x] New component is functional and uses Hooks.
- [x] Component is written in TypeScript.

#### Style

- [x] Styles are added to `NewComponent.modules.scss` file inside the `NewComponent` folder.
- [x] Component uses CSS Modules.
- [x] Design is compatible with [Monday Design System](https://design.monday.com/).
- [x] Styles are defined using [monday-ui-style](https://github.com/mondaycom/monday-ui-style) tokens
- [x] Displays correctly in all the themes

#### Storybook

- [x] Stories were added to `/src/components/NewComponent/__stories__/NewComponent.stories.mdx` file.
- [x] Stories include all flows of using the component.
- [x] Stories implemented using [vibe-storybook-components](https://github.com/mondaycom/vibe-storybook-components) components and tokens.

#### Tests

- [x] Tests are compliant with [TESTING_README.md](TESTING_README.md) instructions.

#### Accessibility

- [x] Component is accessible.
- [x] Component is compatible with [Vibe Accessibility Guidelines](https://style.monday.com/?path=/docs/foundations-accessibility--page)

### CODE REVIEW

**Comment by SoumyadiptoPal** [comment]
@SergeyRoyt Fixed issue #1569

**Review by SergeyRoyt — CHANGES_REQUESTED** [review]
Nice, but besides removal of the cursor bars shouldn't have this "active" state on click or on Tab in Indication mode
image

**Comment by SoumyadiptoPal** [comment]
@SergeyRoyt added pointer-events: none to make the buttons unClickable when isClickable=false

**Review by SergeyRoyt — CHANGES_REQUESTED** [review]
Great!
Let's just update the snapshots - run `npm run test:update` and commit the changes

**Comment by SoumyadiptoPal** [comment]
image
I ran the above command and found only these snapshots were updated. None of them is related to BreadcrumsBar.tsx Can you please help me with the issue?

**Comment by SergeyRoyt** [comment]
> image I ran the above command and found only these snapshots were updated. None of them is related to BreadcrumsBar.tsx Can you please help me with the issue?

Hey, @SoumyadiptoPal !
That's weird, I guess smth got mixed up... I've just ran it locally on your branch and it worked just fine updating` breadcrumbsBar-snapshot-tests.jest.js.snap` and `breadcrumbItem-snapshot-tests.jest.js.snap`. I can push the changes or if you want I can try to help you to do it by your own - whatever you prefer :)

If you want to update the snapshots by yourself I propose you to 
- Check if you are on correct branch
- Check that you don't have any uncommited local changes
- Update master and merge to your branch from it
- Run `npm i` 
- Run `npm run test:update`
Should work I believe 🙏

Also a side note I see that your git history contains tons of unrelated to this PR commits. In general this should be avoided. I propose that on the next PR you'll create you do the following:
- Pull master
- Create new branch from master (it should be a separate branch for each PR) and check it out
- Commit and push your changes to it and create a PR
This way you will always have a clear git history without multiple of "revert" commits

**Pull request closed without merging**
