### PR TITLE
refactor: migrate AttentionBox to typescript

### PR DESCRIPTION
**Pull request by SumeetHaryani**
Add fix for issue #892   

#### Basic
- [ ] Used plop (`npm run plop`) to create a new component.
- [x] PR has description.
- [x] New component is functional and uses Hooks. 
- [x] Component defines [`PropTypes`](https://reactjs.org/docs/typechecking-with-proptypes.html).
#### Style
- [ ] Styles are added to `NewComponent.modules.scss` file inside of the `NewComponent` folder.
- [ ] Component uses CSS Modules.
- [x] Design is compatible with [Monday Design System](https://design.monday.com/).
#### Storybook
- [ ] Stories were added to `/src/NewComponent/__stories__/NewComponent.stories.js` file.
- [x] Stories include all flows of using the component.
#### Tests
- [x] Tests are compliant with [TESTING_README.md](TESTING_README.md) instructions.

### CODE REVIEW

**Comment by SumeetHaryani** [comment]
@orrgottlieb Merge this PR once #924 PR is merged to master

**Comment by orrgottlieb** [comment]
@SumeetHaryani you have conflicts, please solve them and i'll merge

**Comment by hadasfa** [comment]
@SumeetHaryani Can you please resolve the conflicts with IconButton.tsx file?

**Comment by SumeetHaryani** [comment]
@orrgottlieb @hadasfa Sorry for the delay. I have resolved the conflicts

**Review by hadasfa — APPROVED** [review]

**Pull request merged**
