### PR TITLE
fix: change Box/Menu children types to ElementContent

### PR DESCRIPTION
**Pull request by talkor**
https://monday.monday.com/boards/3532714909/pulses/5720753483

### CODE REVIEW

**Review by YossiSaadi — COMMENTED** [review]
Isn't ReactNode more appropriate? It is the one on React.PropsWithChildren

**Comment by talkor** [comment]
> Isn't ReactNode more appropriate? It is the one on React.PropsWithChildren

It's ReactNode

```
export type ElementContent = ReactNode | ReactNode[];
```

**Comment by YossiSaadi** [comment]
> > Isn't ReactNode more appropriate? It is the one on React.PropsWithChildren
> 
> It's ReactNode
> 
> ```
> export type ElementContent = ReactNode | ReactNode[];
> ```

Oh sorry I was without the laptop 😁😅

**Review by YossiSaadi — APPROVED** [review]
😬

**Pull request merged**
