### PR TITLE
docs: RelatedComponents - <VirtualizedGrid> component example #1810

### PR DESCRIPTION
**Pull request by Suraj-Bhandarkar-S**
#1810 

To Add [VirtualizedGrid](https://style.monday.com/?path=/docs/navigation-virtualizedgrid--docs) component example to COMPONENTS_DESCRIPTIONS_ENTRIES array so it'd appear on [components catalog page](https://style.monday.com/?path=/docs/catalog--catalog) 

image

Based on the previous request in #1823 

Added:
- two rows of items
- 50 items in total

### CODE REVIEW

**Review by YossiSaadi — CHANGES_REQUESTED** [review]
Thanks @Suraj-Bhandarkar-S ! :) 
- Please run prettier on the description file and commit the change
- Also, please rebase the branch on Vibe's `master` branch, to drop the two first commits (regarding the `Label` `key` props) to make the PR and the commits in it related to the `VirtualizedGrid` only
- Can also be nice to add a sass module file instead of the inline styling :)

Thanks again for your contribution 🙏🏼

**Comment by Suraj-Bhandarkar-S** [comment]
@YossiSaadi  Thanks for the feedback :)

- Please run prettier on the description file and commit the change - done 
- Also, please rebase the branch on Vibe's master branch, to drop the two first commits (regarding the Label key props) to make the PR and the commits in it related to the VirtualizedGrid only - I had a #1880 now that's merged so I have pulled all the changes from master and raised the PR again, let me know if its still a issue (Kind of new to rebase in Git) So, if changes are still needed will check and update the push. Thanks 
- Can also be nice to add a sass module file instead of the inline styling :) - done

**Comment by YossiSaadi** [comment]
> @YossiSaadi  Thanks for the feedback :)
> 
> - Please run prettier on the description file and commit the change - done 
> - Also, please rebase the branch on Vibe's master branch, to drop the two first commits (regarding the Label key props) to make the PR and the commits in it related to the VirtualizedGrid only - I had a #1880 now that's merged so I have pulled all the changes from master and pushed the commit, let me know if its still a issue (Kind of new to rebase in Git) So, if changes are still needed will check and update the push. Thanks 
> - Can also be nice to add a sass module file instead of the inline styling :) - done



Hi again @Suraj-Bhandarkar-S !

First off, you did awesome work! and it's great to have you as part of our Vibe community.

Since your recent PR includes some commits that aren't directly related to the feature you're working on, and since we want to maintain a clean and focused project history, I kindly ask if we could do some actions to create a cleaner one. We aim to have each PR include only the relevant changes for future reference, if one wants to examine why a change was done. 

No worries, it's a common scenario in collaborative projects, and I'm here to guide you through the process of creating a new branch with just the desired commits. Since you mentioned you're new to Git, here's a straightforward way to do it:

1. In Git, `upstream` refers to the original repository from which a fork is made (in this case, Vibe). It's important to sync your fork with the upstream to get the latest changes.

2. Run `git remote -v` in your terminal (in the context of your forked repo). If you see upstream pointing to Vibe, it's all set. If not, check how you add upstream to the local repo.

3. Checkout to `master`, fetch changes from `upstream` and reset your branch to `upstream/master` to be aligned with it, and from your updated `master`, create a new branch.

5. You can now cherry-pick the commits you want to include in this new branch, and push it :)

After you've prepared your new branch, feel free to open a new pull request. I'm looking forward to seeing your refined contribution!

Thank you for being open to feedback and for your dedication to improving the project. Your efforts are genuinely appreciated!

**Comment by Suraj-Bhandarkar-S** [comment]
Sure, Thank you so much!!! for the steps @YossiSaadi :D will try the following :)

**Pull request closed without merging**
